version: "3.9"

services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
    image: mysql/mysql-server:8.0.23
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306

volumes:
  mysql_data: {}
